### ISSUE TITLE
Missing required parameters for [Route: profile] [URI: profile/{id}].

### ISSUE THREAD

**Issue by c3x** [Brandonxy/imagegram#1]
Local installation:
WSL;
Ubuntu 18.04;
Nginx 1.15.9;
MySQL 10.3.14-MariaDB-1:10.3.14+maria~bionic-log;
PHP 7.2.17-0ubuntu0.18.04.1

Installation successful without errors.

Registration successful (data will added to db), but after reg or when I try to login, I got following error message:

Missing required parameters for [Route: profile] [URI: profile/{id}]. (View: /imagegram/resources/views/layouts/app.blade.php)

**Comment by Brandonxy** [comment]
see commit #5a8b965 where is fixed

**Comment by brandongallardoa** [comment]
see commit https://github.com/Brandonxy/imagegram/commit/5a8b965c36e2c2a0b9a1ae8f31a2a437ecc555de
is fixed now
